---
title: "Summary analyses"
format: html
editor: visual
---

```{r setup}

library(tidyverse)
library(glue)
library(ggthemes)
library(colorspace)

```

```{r}

nrep <- 8
totab <- tibble()

for (type in 1:6) {
  for (i in 0:(nrep-1)) {
    totab <- read_csv(
      glue('../results/03_summary_files/summary_model_{type}.{i}.csv'),
      show_col_types = FALSE
      ) |> 
      mutate(
        model = type,
        idx = i
      ) |> 
      bind_rows(totab)
  }
}

```

```{r}

summarized_table <- totab |> 
  group_by(model, distance, from, to) |> 
  summarise(
    n = sum(n)
  )

summarized_table_with_reversed <- summarized_table |> 
  mutate(
    from_prev = from,
    from = to,
    to = from_prev
  ) |> 
  select(model, distance, from, to, n) |> 
  bind_rows(summarized_table) |> 
  group_by(model, distance, from, to) |> 
  summarise(
    n = sum(n)/2
  )

```

```{r fig.height=15, fig.width=25}

order_pattern <- c('H', 'C', 'HC', 'G', 'HG', 'CG', 'HCG', 'O', 'HO', 'CO', 'GO', 'HCO', 'HGO', 'CGO', 'HCGO')
order_pattern <- c('H', 'C', 'HC', 'G', 'HG', 'CG', 'HCG', 'O', 'HCGO')

color_tab <- expand_grid(
    from = factor(order_pattern, order_pattern),
    to = factor(order_pattern, order_pattern),
    xmin = 0,
    xmax = Inf,
    ymin = -Inf,
    ymax = Inf
    ) |> 
  mutate(
    col = case_when(
      from == to ~ 'diag',
      as.numeric(from) %% 2 == 0 ~ 'gre',
      .default = 'whi'
    )
  )

summarized_table_with_reversed |> 
  group_by(model, from, distance) |> 
  mutate(
    n = n/sum(n),
    model = case_when(
      model == 1 ~ 'm = 0',
      model == 2 ~ 'm = 1',
      model == 3 ~ 'm = 0.25',
      model == 4 ~ 'm = 0.50',
      model == 5 ~ 'm = 0.75',
      model == 6 ~ 'Intermediate t_split'
    )
  ) |> 
  ungroup() |> 
  filter(from %in% order_pattern, to %in% order_pattern) |> 
  mutate(
    to = factor(to, order_pattern),
    from = factor(from, order_pattern)
  ) |> 
  ggplot() +
  geom_rect(
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = col), 
    data = color_tab) +
  geom_smooth(aes(distance, n, color = model), se = FALSE) +
  scale_x_continuous(trans = 'log10') +
  ggh4x::facet_grid2(from~to, scales = "free_y", independent = "y") +
  theme_few() +
  scale_fill_manual(guide = 'none', values = c('grey70', 'grey80', 'white')) +
  scale_colour_manual(name = 'Model', values = c(sequential_hcl(5, palette = 'BluGrn'), 'red'),
                      breaks = c('m = 0', 'm = 1', 'm = 0.25', 'm = 0.50', 'm = 0.75', 'Intermediate t_split')) +
  NULL

```



```{r fig.height=15, fig.width=25}

summarized_table_with_reversed |> 
  group_by(model, from, distance) |> 
  mutate(
    n = n/sum(n),
    model = case_when(
      model == 1 ~ 'm = 0',
      model == 2 ~ 'm = 1',
      model == 3 ~ 'm = 0.25',
      model == 4 ~ 'm = 0.50',
      model == 5 ~ 'm = 0.75',
      model == 6 ~ 'Intermediate t_split'
    )
  ) |> 
  ungroup() |> 
  filter(from %in% order_pattern, to %in% order_pattern) |> 
  mutate(
    to = factor(to, order_pattern),
    from = factor(from, order_pattern)
  ) |> 
  group_by(model, from, to) |> 
  arrange(model, from, to, distance) |> 
  mutate(
    fold_change = n/mean(n[(n()-2):n()])
  ) |> 
  ggplot() +
  geom_rect(
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = col), 
    data = color_tab) +
  geom_smooth(aes(distance, fold_change, color = model), se = FALSE) +
  scale_x_continuous(trans = 'log10') +
  ggh4x::facet_grid2(from~to, scales = "free_y", independent = "y") +
  theme_few() +
  scale_fill_manual(guide = 'none', values = c('grey70', 'grey80', 'white')) +
  scale_colour_manual(name = 'Model', values = c(sequential_hcl(5, palette = 'BluGrn'), 'red'),
                      breaks = c('m = 0', 'm = 1', 'm = 0.25', 'm = 0.50', 'm = 0.75', 'Intermediate t_split')) +
  NULL

```





